[install]
is_configured = 0
state = enabled
build = 1

[launcher]
author = wolf359-ai
description = Technology add-on: sourcetypes, indexes (lab), and field mapping for factory line shift and personnel events.
version = 0.1.0

[package]
id = TA-factory_line
check_for_updates = false

[ui]
is_visible = 0
label = Factory Line Operations Add-on

[id]
name = TA-factory_line
version = 0.1.0
