[factory_shift_clock]
search = sourcetype=factory:shift:clock
color = 0x006D9C

[factory_shift_assignment]
search = sourcetype=factory:shift:assignment
color = 0x006D9C

[factory_personnel_presence]
search = sourcetype=factory:personnel:presence
color = 0x5C2D91

[factory_personnel_exception]
search = sourcetype=factory:personnel:exception
color = 0xC43E1C

[factory_line_state]
search = sourcetype=factory:line:state
color = 0x14805E

[factory_line_down]
search = sourcetype=factory:line:state state_value=down
color = 0xC43E1C

[factory_line_production]
search = sourcetype=factory:line:production
color = 0x14805E

[factory_line_downtime]
search = sourcetype=factory:line:downtime
color = 0xC43E1C
