[good_count]
INDEXED_VALUE = true

[reject_count]
INDEXED_VALUE = true

[total_count]
INDEXED_VALUE = true

[downtime_minutes]
INDEXED_VALUE = true

[cycle_time]
INDEXED_VALUE = true

[ideal_cycle_time]
INDEXED_VALUE = true

[oee]
INDEXED_VALUE = true

[fill_pct]
INDEXED_VALUE = true
