# Lab / single-instance Enterprise only.
# Splunk Cloud: create these indexes in ACS or Splunk Web. Do not expect
# this file to be applied automatically on Cloud.

[factory_ops]
homePath = $SPLUNK_DB/factory_ops/db
coldPath = $SPLUNK_DB/factory_ops/colddb
thawedPath = $SPLUNK_DB/factory_ops/thaweddb
frozenTimePeriodInSecs = 34128000
repFactor = auto

[factory_workforce]
homePath = $SPLUNK_DB/factory_workforce/db
coldPath = $SPLUNK_DB/factory_workforce/colddb
thawedPath = $SPLUNK_DB/factory_workforce/thaweddb
frozenTimePeriodInSecs = 34128000
repFactor = auto

[factory_summary]
homePath = $SPLUNK_DB/factory_summary/db
coldPath = $SPLUNK_DB/factory_summary/colddb
thawedPath = $SPLUNK_DB/factory_summary/thaweddb
frozenTimePeriodInSecs = 65700000
repFactor = auto
